### ISSUE TITLE
installation instructions for Mac?

### ISSUE THREAD

**Issue by JRRMDSG** [IntelligenceX/SDK#11]
I've been suffering with this transform because I love your tool but for the life of my I can't get the gosh darn thing to work.

Do you have Mac specific instructions and I've overlooked them?

Thanks.

**Comment by Kleissner** [comment]
Unfortunately we don't and we don't have a mac at hand to try it out.
Did you follow the instructions 1 by 1? Is there any particular step that fails? Any error messages?

**Comment by JRRMDSG** [comment]
I thought I was able to translate the installation correctly, but am not quite sure where I failed on the connecting the transform to the Py3 folder.  The output error that I'm receiving each time is "-Error running local transform: java.io.IOException: Cannot run program "Users/<me>/intelx-maltego/Maltego Transforms/config/Servers" (in directory "Users/<me>/intelx-maltego/Python"): error=13, Permission denied"

I guess now that I'm typing this out, I'm wondering where I goofed.

Looking forward to your feedback

**Comment by Kleissner** [comment]
The white space in your path ("Maltego Transforms") could be the problem.
![image](https://user-images.githubusercontent.com/13511064/103457275-1143eb00-4cfe-11eb-8df5-d16226c32ae2.png)

**Comment by JRRMDSG** [comment]
I fixed the white space in the dir, updated the file path in the transform server directory, and I'm not receiving any type of error message popups now.  Thanks for pointing that out.
