### ISSUE TITLE
phonebook data issue

### ISSUE THREAD

**Issue by StealerCook** [IntelligenceX/SDK#12]
Hi, 
phonebook website provides more count of email ID, while querying phonebook through python api the count of email IDs are limited (less than the counts collected from website). Is there any solution for it?

Note: Checked with changing max_result limit too.. But I could see the difference.

**Comment by Kleissner** [comment]
Can you give a specific example including the python api code?
This is likely due to different limits and timeouts. A paid account has increased limits.

**Comment by telolet347** [comment]
yes

**Comment by StealerCook** [comment]
Ok. Mine is the free ID.
