### ISSUE TITLE
OpenAPI/Swagger Documentation

### ISSUE THREAD

**Issue by cmlh** [IntelligenceX/SDK#527]
Convert [Intelligence X API.pdf](https://github.com/IntelligenceX/SDK/blob/master/Intelligence%20X%20API.pdf) to OpenAPI/Swagger.

**Comment by rickwysocki** [comment]
Hey there! If this is still open, I'd be happy to give it a shot.

**Comment by rickwysocki** [comment]
@cmlh Sure, I'm happy to do that. I'll start working on it this weekend and submit a pull request once I've finished the openapi spec.

**Comment by rickwysocki** [comment]
Apologies, but some things have come up and I won't be able to work on this.

**Comment by Azuris2** [comment]
Hello! I'm kinda new to API documentation, but I'd like to give the specification doc a try. 
Would that be alright with you?

**Comment by Azuris2** [comment]
That's great! I've begun crafting a rough skeleton of the specs, but it seems that I might have gotten my IP blacklisted while trying to run some API calls through postman T_T

I've sent in an email but in the meantime I should still be able to continue working on it though.

**Comment by Azuris2** [comment]
Just an update @cmlh: 
I've gotten my access issues cleared up and I think I am about mostly done with the docs. I'll need just a little more time to do some cleaning/testing and would be able to submit a pull request then. 

Cheers!
