### ISSUE TITLE
Successful Import, but error output from transform

### ISSUE THREAD

**Issue by terminatordoink** [IntelligenceX/SDK#8]
Receive this error
<MaltegoMessage><MaltegoTransformResponseMessage><Entities></Entities><UIMessages><UIMessage MessageType="PartialError">Error: Invalid return character or leading space in header: x-key</UIMessage></UIMessages></MaltegoTransformResponseMessage></MaltegoMessage>

**Comment by Kleissner** [comment]
Did you type in an API key during installation? If you did, did it contain any extra space characters?
